apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722projectpart3.azurecr.io/book_catalog:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: "postgresql://sit722projectpart3_user:kk7ISoQi57rijke66eJPXJbTV8Xe6FQJ@dpg-crjutnl2ng1s73flchbg-a.oregon-postgres.render.com/sit722projectpart3"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: sit722projectpart3.azurecr.io/inventory_management:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: "postgresql://sit722projectpart3_user:kk7ISoQi57rijke66eJPXJbTV8Xe6FQJ@dpg-crjutnl2ng1s73flchbg-a.oregon-postgres.render.com/sit722projectpart3"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001